[package]
name = "mario-rs"
version = "0.1.0"
authors = ["Michael Iskandarani <mike.iskandarani@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
specs = "0.16"