[package]
authors = ["Michael Iskandarani <mike.iskandarani@gmail.com>"]
edition = "2018"
name = "mario-rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
num-traits = "0.2.12"
specs = "0.16"
